{% set component_name = "utils" %}
{% set base_name = "libignition-" + component_name %}
{% set version = "1_1.5.1" %}
{% set version_clean = version.split('_')[1] %}
{% set major_version = version_clean.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_clean }}

source:
  - url: https://github.com/ignitionrobotics/ign-{{ component_name }}/archive/ignition-{{ component_name }}{{ version }}.tar.gz
    sha256: fba9d1d3cdafa73148697433bba206aa1251d24c0afa22f09bb3289092021449

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-cmake2
    - cli11
  run:
    - cli11

test:
  commands:
    - test -f ${PREFIX}/include/ignition/{{ component_name }}{{ major_version }}/ignition/{{ component_name }}.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-{{ component_name }}{{ major_version }}/ignition-{{ component_name }}{{ major_version }}-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\\{{ component_name }}{{ major_version }}\\ignition\\{{ component_name }}.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ignition-{{ component_name }}{{ major_version }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ignition-{{ component_name }}{{ major_version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-{{ component_name }}{{ major_version }}\\ignition-{{ component_name }}{{ major_version }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-{{ component_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Classes and functions for robot applications.

extra:
  feedstock-name: {{ base_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
